### PR TITLE
removes view heights #159

### LINKED ISSUE #159: Get rid of view height values that are no longer being used

### PR DESCRIPTION
**Pull request by sssoja**
### What changes have you made?
- removed `vh` usage in all of the `main` tags and replaced with `height: 100%` 
- although there is a `height: 100%` in the `body` class of Global Style, it wasn't showing as inherited on some of the components so for consistency that's why I've kept an attribute of `height: 100%` on each of the `Main` tags
- where `height: 100%` is a bit high, I've wrapped some components in a `Container` in order to set height as a % of the `Main` 

### Which issue(s) does this PR fix?

Fixes #159 

### How to test
- check for any unused `vh` attributes
- move through the site and check that the height of each page looks consistent

### CODE REVIEW

**Comment by Jbarget** [comment]
Before:
image

After:
image

the padding on the body of global styles has been lost

**Comment by sssoja** [comment]
hey @Jbarget check #156 which has already been merged. this branch was created before the merge took place which is why the padding isn't showing.

**Comment by sssoja** [comment]
are you okay to approve?

**Comment by Jbarget** [comment]
In that case, its best to merge the latest work on the `develop` branch into this branch (so/remove-viewheights) and then push back up to `so/remove-viewheights` on github so that i can preview what the app looks like once this would be merged in. If you need a step by step instructions let me know

**Comment by sssoja** [comment]
Okey dokey

**Comment by sssoja** [comment]
I made it my mission this morning to be at one with Vim and for the first time, it worked. Happy :)

Lemme know if the preview looks okay now @Jbarget

**Review by Jbarget — APPROVED** [review]

**Pull request merged**
