### PR TITLE
adds background to all pages

### LINKED ISSUE #151: Fix background image on all pages
the background image still needs to be applied to all pages

### PR DESCRIPTION
**Pull request by sssoja**
### What changes have you made?
- added backgrounds to all pages 
- used a different background to differentiate the nav menu overlay 
- reduced the file size of `background.jpg` from a whopping 32 mb to 3.4 mb but this is still too heavy and is slowing down the site 

### Which issue(s) does this PR fix?

Fixes #151 

### Screenshots (if there are design changes)
Screenshot 2020-10-09 at 12 36 01

### How to test
- nav through the site and see that the background image appears on every page 
- suggestions on speeding up load times mucho welcome

### CODE REVIEW

**Comment by Jbarget** [comment]
id say this PR makes the website too slow to be considered usable, rather than fixing in another PR reduce the size of the background files to below 1mb and lets see how it looks then

**Comment by sssoja** [comment]
@Jbarget not sure its as straightforward as putting the images through another round of compression, for me this doesn't work no matter which compressor i use. I've been looking at npm packages and found this [one](https://www.npmjs.com/package/compressorjs), it looks like you can set the compression manually here. What do you think about this?

**Comment by Jbarget** [comment]
Has the "alpha" logo been compressed?
its 1.1MB

essentially the website is really slow for me, is it the same for you?
image

>What do you think about this?

Try it and see what happens

**Comment by Jbarget** [comment]
woah and all the icons

**Review by Jbarget — APPROVED** [review]
Approving this and created a new ticket #179 to work against for the optimisation of assets

**Comment by sssoja** [comment]
I've responded on the new ticket #179 @Jbarget

**Comment by Jbarget** [comment]
i've approved this so this can go in, if we can work on the new ticket soon since I would consider it a priority to get the loading/usability of the website to a good level

**Comment by sssoja** [comment]
Okay i'm on it but its taking a while because the compression limit is often higher than 1MB. Did you manage to take a look at #140?

**Comment by sssoja** [comment]
I'm using compress-or-die.com/ by the way

**Pull request merged**
