### PR TITLE
creates advertising page

### LINKED ISSUE #7: Create page: Advertising

### PR DESCRIPTION
**Pull request by sssoja**
### What changes have you made?

- created advertising page 
- reduced images to 720px 

(Designs approved by Aitor on 29/09, new high res image to follow but don't have a date for this)

### Which issue(s) does this PR fix?

Fixes #7 

### Screenshots (if there are design changes)
Screenshot 2020-09-25 at 18 44 24

localhost_3000_advertising(iPhone 6_7_8)

### How to test
open the Advertising page and check:
- the images appear side by side on desktop with some text underneath
- the images and text appear as one column on mobile 
- the translation works on both texts

### CODE REVIEW

**Comment by Jbarget** [comment]
it seems the Route for Advertising needs to be added for App.tsx, which im confused about since i definitely got it working last time without that. 

Can you check with Aitor whether he's happy with this page as it is

**Comment by sssoja** [comment]
No he's happy @Jbarget as approved on 29/09

**Comment by sssoja** [comment]
I've added the Route back in @Jbarget it probably got removed due to merge conflicts.

**Comment by sssoja** [comment]
@Jbarget this is showing as assigned to me but not sure what the issue is?

**Review by Jbarget — APPROVED** [review]
yep yep sorry it slipped

**Pull request merged**
