### PR TITLE
Eye interaction project

### LINKED ISSUE #15: Project 6: Eye interaction
image

image

### PR DESCRIPTION
**Pull request by Jbarget**
### What changes have you made?

- added the eye project

### Which issue(s) does this PR fix?

Fixes #15 

### Screenshots (if there are design changes)
image

### How to test
- change `launchDate` in `Eye.tsx` to a date in the past
- should see eye data
- should be able to change data set
- if you click on an eye the data should appear in the top RH corner

### CODE REVIEW

**Review by sssoja — COMMENTED** [review]
Honestly excellent job.

I don't know if you intended for this to look so good on mobile but I took the liberty of just adding in a lower font size on the country data so that everything fits in nicely on the screen.

Screenshot 2020-11-26 at 09 50 06
 
Won't approve in case @mantagen wants to have a look.

**Comment by Jbarget** [comment]
haha this definitely wasnt built mobile first

**Comment by Jbarget** [comment]
@sssoja im gonna merge and if Mantagen wants to suggest changes he can retrospectively make comments 👍

**Comment by mantagen** [comment]
@jbarget @sssoja soz had a busy day today, will have a cheeky look tomorrow

**Pull request merged**
