### PR TITLE
adds Facebook pixel code

### LINKED ISSUE #354: Add Facebook pixel code for tracking

### PR DESCRIPTION
**Pull request by sssoja**
### What changes have you made?
- added a Facebook pixel code to the `index.html` so that traffic coming from paid Facebook ads can be measured
- updated a couple of meta tags 

### Which issue(s) does this PR fix?

Fixes #354

### How to test
- go to index.html
- make sure there is a Facebook pixel at the bottom of the header section, just above the closing head tag

### CODE REVIEW

**Comment by sssoja** [comment]
https://www.facebook.com/business/help/952192354843755?id=1205376682832142

**Comment by Jbarget** [comment]
2 project pages have been deleted?
can the `id` in the facebook pixel code be put in the .env? and used that way

**Comment by sssoja** [comment]
- 2 project pages have been deleted? yeah they were duplicates/leftover files
- can the id in the facebook pixel code be put in the .env? and used that way? not exactly, the code snippet itself is JavaScript in HTML, rather than one abstractable string. As a half solution, I've taken out the `src` url from the code snippet and moved it into the .env and assigned it to the variable `FACEBOOK_SRC_URL`

**Comment by sssoja** [comment]
Approving this one as its time-sensitive I've reversed the changes on the .env file just in case - happy to look at it again at another time

**Pull request merged**
